input {
  tcp {
    port => 5000
    codec => line
  }
}

filter {
  mutate {
    add_field => {
      "application" => "calculator"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "calculator-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}